In [5]:
import numpy as np

In [6]:
km = np.loadtxt('carros-km.txt')
anos = np.loadtxt('carros-anos.txt', dtype = int)

OSError: carros-km.txt not found.

In [14]:
#obtendo a quilometragem média por ano
km_media = km / (2020 - anos)

In [17]:
km_media

array([2.61235294e+03, 1.96965517e+02, 1.23743333e+03, 0.00000000e+00,
       1.83978571e+03, 1.34100000e+03, 0.00000000e+00, 7.05445455e+03,
       9.91970000e+03, 4.21977778e+03, 7.14388889e+02, 6.19384615e+02,
       4.72489474e+03, 0.00000000e+00, 3.76881818e+03, 2.89017500e+04,
       5.80612500e+03, 0.00000000e+00, 9.27150000e+03, 5.05766667e+03,
       5.62183333e+03, 0.00000000e+00, 3.77226923e+03, 3.55031034e+03,
       0.00000000e+00, 0.00000000e+00, 1.44875000e+03, 0.00000000e+00,
       3.26933333e+03, 3.25451724e+03, 1.31143478e+03, 2.13328000e+03,
       8.86000000e+03, 1.16579310e+03, 1.51140000e+04, 1.75900000e+03,
       0.00000000e+00, 0.00000000e+00, 5.02363636e+02, 0.00000000e+00,
       1.33450000e+04, 2.39776471e+03, 0.00000000e+00, 4.79455556e+03,
       0.00000000e+00, 5.41944444e+02, 4.37156250e+03, 1.26052632e+02,
       0.00000000e+00, 4.72641176e+03, 7.77763636e+03, 3.60685714e+03,
       3.38580000e+03, 6.71050000e+03, 3.53450000e+03, 3.11565385e+03,
      

In [18]:
type(km_media)

numpy.ndarray

In [26]:
#transformar um número de tipo numérico em string
a = 10
b = 'python é '
str(a)

'10'

In [27]:
type(str(a))

str

In [28]:
b + str(a)

'python é 10'

In [29]:
#transformar ponto flutuante em inteiro
c =3.214234
int(c)
#NÃO É ARREDONDAMENTO

3

In [31]:
acessorios = ['bagulhos', 'parara', 'tudobom', 'maravilha']
acessorios[-1]

'maravilha'

In [32]:
acessorios.pop()

'maravilha'

In [33]:
acessorios

['bagulhos', 'parara', 'tudobom']

In [35]:
acessorios.pop(1)

'parara'

In [36]:
acessorios

['bagulhos', 'tudobom']

In [37]:
#criar nova lista com mesmos itens
acessorios_2 = acessorios.copy()

In [43]:
acessorios_2.append('tois')
acessorios_2

['bagulhos', 'tudobom', 'tois', 'tois', 'tois', 'tois', 'tois']

In [44]:
acessorios

['bagulhos', 'tudobom']

In [45]:
Acessorios = [
    'Rodas de liga', 
    'Travas elétricas', 
    'Piloto automático',
    'Bancos de couro',
    'Ar condicionado'
]

In [55]:
Acessorios.append('Airbag')
Acessorios.sort()
Acessorios.pop()
Acessorios.append('Vidros Elétricos')
Acessorios

['Airbag',
 'Airbag',
 'Ar condicionado',
 'Bancos de couro',
 'Nao identifcaenor',
 'Piloto automático',
 'Rodas de liga',
 'Travas elétricas',
 'Vidros Elétricos',
 'Vidros Elétricos',
 'Vidros Elétricos',
 'Vidros Elétricos',
 'Vidros Elétricos',
 'Vidros Elétricos',
 'Vidros Elétricos']

In [56]:
Acessorios = [
    'Rodas de liga', 
    'Travas elétricas', 
    'Piloto automático',
    'Bancos de couro',
    'Ar condicionado'
]

In [61]:
for  item in Acessorios:
    print(item)

Rodas de liga
Travas elétricas
Piloto automático
Bancos de couro
Ar condicionado


In [62]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [63]:
for i in range(10):
    print(i**2)

0
1
4
9
16
25
36
49
64
81


In [67]:
quadrado = [0]
for i in range(10):
    quadrado.append(i ** 2)
quadrado

[0, 0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [69]:
dados = [ 
    ['A', 'B', 'C'],
    ['D', 'E', 'F'],
    ['G', 'H', 'I']
]

In [74]:
resultado = []
for lista in dados:    
    resultado.append(lista)
resultado

[['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']]

In [71]:
resultado_2 = []
for lista in dados:
    resultado_2 += lista
resultado_2

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']

In [80]:
for lista in dados:
    if(lista[2]=='C'):
        print('tmj')

tmj


In [82]:
#comparando listas com arrays Numpy

np_array = np.arange(1000000)
py_list = list(range(1000000))

In [84]:
%time for _ in range(100): np_array *= 2

Wall time: 177 ms


In [85]:
%time for _ in range(100): py_list = [x * 2 for x in py_list]

Wall time: 20.4 s


In [92]:
#operações aritméticas com arrays numpy

km = np.array([46418., 5712., 37123., 0., 25257])
anos = np.array([2005, 1991, 1990, 2019, 2006])

In [93]:
idade = 2020 - anos
idade

array([15, 29, 30,  1, 14])

In [95]:
km_media = km / idade
km_media

array([3094.53333333,  196.96551724, 1237.43333333,    0.        ,
       1804.07142857])

In [7]:
#operações com arrays de duas dimensões

dados = np.array([km, anos])
dados

NameError: name 'km' is not defined

In [117]:
dados.shape

(2, 5)

In [118]:
dados[0]

array([46418.,  5712., 37123.,     0., 25257.])

In [119]:
km_media_2 = dados[0] / (2020 - dados[1])
km_media_2

array([3094.53333333,  196.96551724, 1237.43333333,    0.        ,
       1804.07142857])

In [8]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
item = 6
index = item - 1
contador[index]

NameError: name 'contador' is not defined

In [122]:
dados[1,2]

1990.0

In [123]:
#selecionar informações dando passo

contador[1:8:2]

array([1, 3, 5, 7])

In [124]:
dados[:,1:4]

array([[ 5712., 37123.,     0.],
       [ 1991.,  1990.,  2019.]])

In [125]:
dados[:,1:4:2]

array([[5712.,    0.],
       [1991., 2019.]])

In [126]:
contador > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [127]:
dados[1] > 2000

array([ True, False, False,  True,  True])

In [128]:
dados[:, dados[1] > 2000 ]

array([[46418.,     0., 25257.],
       [ 2005.,  2019.,  2006.]])

In [10]:
#atributos e métodos de arrays numpy

''' dados.shape
dados.ndim #dimensão
dados.size
dados.dtype #mostra o tipo
dados.T #transpõe
dados.tolist() #tranformar em list'''
print(contador)
contador.reshape((2,5), order ='f')



[0 1 2 3 4 5 6 7 8 9]


array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [154]:
novos_dados = dados.copy()
novos_dados

array([[46418.,  5712., 37123.,     0., 25257.],
       [ 2005.,  1991.,  1990.,  2019.,  2006.]])

In [158]:
novos_dados.resize((3,5), refcheck=False)
novos_dados

array([[46418.,  5712., 37123.,     0., 25257.],
       [ 2005.,  1991.,  1990.,  2019.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [160]:
novos_dados[2] = novos_dados[0] / 2020 - novos_dados[1]
novos_dados

array([[46418.        ,  5712.        , 37123.        ,     0.        ,
        25257.        ],
       [ 2005.        ,  1991.        ,  1990.        ,  2019.        ,
         2006.        ],
       [-1982.02079208, -1988.17227723, -1971.62227723, -2019.        ,
        -1993.49653465]])

In [163]:
#estatísticas descritivas com Numpy

anos = np.loadtxt('carros-anos.txt', dtype = int)
km = np.loadtxt('carros-km.txt')
valor = np.loadtxt('carros-valor.txt')

In [165]:
#transformar arrays de uma dimensão em colunas de um array 
#bidimensional

dataset = np.column_stack((anos, km, valor))
dataset

array([[2.0030000e+03, 4.4410000e+04, 8.8078640e+04],
       [1.9910000e+03, 5.7120000e+03, 1.0616194e+05],
       [1.9900000e+03, 3.7123000e+04, 7.2832160e+04],
       [2.0190000e+03, 0.0000000e+00, 1.2454907e+05],
       [2.0060000e+03, 2.5757000e+04, 9.2612100e+04],
       [2.0120000e+03, 1.0728000e+04, 9.7497730e+04],
       [2.0190000e+03, 0.0000000e+00, 5.6445200e+04],
       [2.0090000e+03, 7.7599000e+04, 1.1231044e+05],
       [2.0100000e+03, 9.9197000e+04, 1.2071627e+05],
       [2.0110000e+03, 3.7978000e+04, 7.6566490e+04],
       [2.0020000e+03, 1.2859000e+04, 7.1647590e+04],
       [2.0070000e+03, 8.0520000e+03, 7.3919530e+04],
       [2.0010000e+03, 8.9773000e+04, 1.1273299e+05],
       [2.0190000e+03, 0.0000000e+00, 5.3183380e+04],
       [2.0090000e+03, 4.1457000e+04, 1.2748842e+05],
       [2.0160000e+03, 1.1560700e+05, 5.9910400e+04],
       [2.0120000e+03, 4.6449000e+04, 6.1118590e+04],
       [2.0190000e+03, 0.0000000e+00, 8.8552390e+04],
       [2.0160000e+03, 3.708

In [166]:
dataset.shape

(258, 3)

In [169]:
np.mean(dataset, axis = 0) # média por coluna

array([ 2007.51162791, 44499.41472868, 98960.51310078])

In [172]:
np.mean(dataset[:, 1])

44499.41472868217

In [173]:
np.mean(dataset[:, 2])

98960.51310077519

In [176]:
np.std(dataset, axis = 0)

array([9.70703915e+00, 3.98598270e+04, 2.97541012e+04])

In [177]:
dataset[:,1].sum()

11480849.0